FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /App
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY Gateway.WebAPI/*.sln ./Gateway.WebAPI/
COPY Gateway.WebAPI/Gateway.WebAPI/Gateway.WebAPI.csproj ./Gateway.WebAPI/Gateway.WebAPI/
COPY SharedModules/SharedModules.csproj ./SharedModules/

RUN dotnet restore Gateway.WebAPI/Gateway.WebAPI.sln

COPY Gateway.WebAPI/ ./Gateway.WebAPI/
COPY SharedModules/ ./SharedModules/

WORKDIR /src/Gateway.WebAPI
FROM build AS publish
RUN dotnet publish -c $BUILD_CONFIGURATION -o /App/publish 

FROM base AS final

EXPOSE 5179

WORKDIR /App
COPY --from=publish /App/publish .
ENTRYPOINT ["dotnet", "Gateway.WebAPI.dll"]

