// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Surveyor.DAL;

#nullable disable

namespace Surveyor.DAL.Migrations
{
    [DbContext(typeof(SurveyorDBContext))]
    [Migration("20240604070224_Added_Report_Estimated_loss")]
    partial class Added_Report_Estimated_loss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Surveyor.DAL.SurveyReport", b =>
                {
                    b.Property<string>("ClaimId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccidentDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepreciationCost")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedLoss")
                        .HasColumnType("int");

                    b.Property<int>("LabourCharges")
                        .HasColumnType("int");

                    b.Property<int>("PartsCost")
                        .HasColumnType("int");

                    b.Property<int>("PolicyClause")
                        .HasColumnType("int");

                    b.Property<string>("PolicyNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<int>("VehicleAge")
                        .HasColumnType("int");

                    b.HasKey("ClaimId")
                        .HasName("Pk_SurveyReport");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
