@Testing_HostAddress = http://localhost:5179

###
GET {{Testing_HostAddress}}/api/claims
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWFubmFwcml0YW1qaXQiLCJqdGkiOiI2YmQyODA1Ny02ODJhLTQ1NzEtOTNkZC02MWJiM2YxNGNhMzciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJJbnN1cmFuY2VDb21wYW55IiwiZXhwIjoxNzIxODE3NzU5LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUxNzkiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUxNzkifQ.m9nQCKAvfm24uwEO5yuBLwm6COOtmF19QRemR-cKA4k
###
GET {{Testing_HostAddress}}/api/claims/closed




###
POST {{Testing_HostAddress}}/api/claims/addclaim
Content-Type: application/json

{
  "policyNo": "SO18824",
  "estimatedLoss": 6000,
  "dateOfAccident": "2024-05-30"
}

###
GET {{Testing_HostAddress}}/IRDA/claimStatus/report/5/2024

###
GET {{Testing_HostAddress}}/api/surveyReport/CLSO182024

###
PATCH  {{Testing_HostAddress}}/api/surveyReport/CLSO182024
Content-Type: application/json

{
    "labourCharges":2100,
    "partsCost":4500
}
