using System.Globalization;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using SharedModules;

namespace InsuranceCompany.DAL;

/// <summary>
/// EF Core DbContext for the InsuranceCompany domain.
/// Provides access to database sets (Fees, Policies, Surveyors, ClaimDetails),
/// configures entity mappings, relationships, default values and seeds initial data.
/// </summary>
public class InsuranceCompanyDBContext:DbContext
{

    /// <summary>
    /// Constructor used by dependency injection. The DbContextOptions object
    /// carries configuration such as the provider (SQL Server, SQLite, etc.) and the connection string.
    /// Passing options to the base DbContext constructor initializes EF Core with that configuration.
    /// </summary>
    public InsuranceCompanyDBContext(DbContextOptions<InsuranceCompanyDBContext>options):base(options) {} 


    /// <summary>
    /// Represents the Fees table. Use this DbSet to query or save Fee entities.
    /// </summary>
    public virtual DbSet<Fee> Fees { get; set; }

    /// <summary>
    /// Represents the Policies table. PolicyNo is used as the primary key.
    /// </summary>
    public virtual DbSet<Policy> Policies { get; set; } 

    /// <summary>
    /// Represents the Surveyors table. SurveyorId is configured to be generated on add.
    /// </summary>
    public virtual DbSet<Surveyor> Surveyors { get; set; } 

    /// <summary>
    /// Represents the ClaimDetails table. Claims link to Policy and optionally to a Surveyor.
    /// </summary>
    public virtual DbSet<ClaimDetail> ClaimDetails { get; set; } 




    /// <summary>
    /// Configure EF Core model mappings, relationships, default values and seed data.
    /// Explanation of common methods used below:
    /// - Entity<T>()       : starts configuration for entity type T.
    /// - HasKey(expr)      : configures the primary key for the entity.
    /// - HasName(string)   : gives a specific name to a key/constraint (useful in migrations).
    /// - HasMany(nav)      : configures a collection navigation (one-to-many).
    /// - WithOne(nav)      : configures the reference navigation on the other side.
    /// - IsRequired()      : enforces that the FK is required (NOT NULL).
    /// - HasForeignKey(expr): specifies which property is the foreign key.
    /// - OnDelete(policy)  : configures cascade behavior when the principal is deleted.
    /// - Property(expr)    : configures a scalar property on the entity.
    /// - ValueGeneratedOnAdd(): indicates the value is generated by the DB on insert (identity).
    /// - HasDefaultValue(v): sets a default value for a column when inserting new rows.
    /// - HasData(...)      : seeds initial data used by migrations to populate the table.
    ///
    /// Also used helpers:
    /// - DateOnly.FromDateTime(DateTime) and DateTime.ParseExact(...) are used to parse and create DateOnly values consistently.
    ///   DateTime.ParseExact(string, format, CultureInfo.InvariantCulture) parses a string to a DateTime using the specified format
    ///   and invariant culture to avoid locale-dependent parsing differences.
    /// </summary>
    /// <param name="modelBuilder">ModelBuilder instance used to configure the model.</param>
    protected override void OnModelCreating(ModelBuilder modelBuilder){
        // Policy: configure primary key and constraint name for clarity in migrations.
        modelBuilder.Entity<Policy>().HasKey(p => p.PolicyNo).HasName("Pk_Policy");
        // Set up one-to-many: Policy (principal) -> ClaimDetails (dependent).
        // WithOne(p => p.Policy) indicates each ClaimDetail references a Policy.
        // IsRequired() makes the PolicyNo FK NOT NULL on ClaimDetail.
        // OnDelete(DeleteBehavior.Cascade) means deleting a Policy removes related ClaimDetails.
        modelBuilder.Entity<Policy>().HasMany(p => p.ClaimDetails).WithOne(p => p.Policy).IsRequired().HasForeignKey(c => c.PolicyNo).OnDelete(DeleteBehavior.Cascade).HasConstraintName("Fk_Policy_ClaimDetail");

        // Surveyor: primary key and relationship configuration.
        // HasMany/WithOne maps Surveyor -> ClaimDetails.
        // OnDelete(DeleteBehavior.SetNull) means if a Surveyor is deleted, ClaimDetails remain but their SurveyorID FK is set to NULL.
        modelBuilder.Entity<Surveyor>().HasKey(s => s.SurveyorId).HasName("Pk_Surveyor");
        modelBuilder.Entity<Surveyor>().HasMany(s => s.ClaimDetails).WithOne(c => c.Surveyor).HasForeignKey(c => c.SurveyorID).OnDelete(DeleteBehavior.SetNull).HasConstraintName("Fk_Surveyor_ClaimDetail");
        // ValueGeneratedOnAdd sets SurveyorId to be database-generated (identity/auto-increment).
        modelBuilder.Entity<Surveyor>().Property(s => s.SurveyorId).ValueGeneratedOnAdd();
        // HasDefaultValue(0) initializes TimesAllocated to zero for new Surveyor rows.
        modelBuilder.Entity<Surveyor>().Property(s => s.TimesAllocated).HasDefaultValue(0);

        // Fee: primary key and identity generation.
        modelBuilder.Entity<Fee>().HasKey(f => f.FeeId).HasName("Pk_Fee");
        modelBuilder.Entity<Fee>().Property(f => f.FeeId).ValueGeneratedOnAdd();

        // ClaimDetail: primary key and default values for several columns to ensure predictable initial state.
        // WITHDRAWSTATUS.NOSTATUS is set as the default withdraw claim enum value.
        // InsuranceCompanyApproval defaults to false so claims are unapproved by default.
        // ClaimStatus defaults to ClaimStatus.Open to mark new claims as open.
        modelBuilder.Entity<ClaimDetail>().HasKey(f => f.ClaimId).HasName("Pk_ClaimDetail");
        modelBuilder.Entity<ClaimDetail>().Property(c => c.WithdrawClaim).HasDefaultValue(WITHDRAWSTATUS.NOSTATUS);
        modelBuilder.Entity<ClaimDetail>().Property(c => c.InsuranceCompanyApproval).HasDefaultValue(false);
        modelBuilder.Entity<ClaimDetail>().Property(c => c.ClaimStatus).HasDefaultValue(ClaimStatus.Open);

        // Seed Surveyor data:
        // HasData provides initial rows inserted during migrations or ensured at DB creation.
        // Seeded IDs must match configured generation strategy to avoid conflicts.
        modelBuilder.Entity<Surveyor>().HasData([
            new Surveyor { SurveyorId = 1, FirstName = "R", LastName = "K", EstimateLimit = 6000 },
            new Surveyor { SurveyorId = 2, FirstName = "K", LastName = "R", EstimateLimit = 15000 },
            new Surveyor { SurveyorId = 3, FirstName = "P", LastName = "M", EstimateLimit = 50000 },
            new Surveyor { SurveyorId = 4, FirstName = "S", LastName = "M", EstimateLimit = 15000 }
        ]);

        // Seed Policy data:
        // DateOnly.FromDateTime(DateTime.ParseExact(...)) ensures the date is parsed in a culture-invariant way.
        // This avoids locale-dependent parsing issues and stores only the date portion.
        modelBuilder.Entity<Policy>().HasData([
            new Policy { PolicyNo = "MA33724", InsuredFirstName = "Pritamjit", InsuredLastName = "Manna", DateOfInsurance = DateOnly.FromDateTime(DateTime.ParseExact("2024-03-14", "yyyy-MM-dd", CultureInfo.InvariantCulture)), EmailId = "pm@cognizant.com", VehicleNo = "HR26DK8337", status = true },
            new Policy { PolicyNo = "PR88624", InsuredFirstName = "Manna", InsuredLastName = "Pritamjit", DateOfInsurance = DateOnly.FromDateTime(DateTime.ParseExact("2024-03-13", "yyyy-MM-dd", CultureInfo.InvariantCulture)), EmailId = "mp@cognizant.com", VehicleNo = "WB31W6886", status = true },
            new Policy { PolicyNo = "SO18824", InsuredFirstName = "Souvik", InsuredLastName = "Maity", DateOfInsurance = DateOnly.FromDateTime(DateTime.ParseExact("2024-03-15", "yyyy-MM-dd", CultureInfo.InvariantCulture)), EmailId = "ms@cognizant.com", VehicleNo = "WB32U3188", status = false },
        ]);

        // Seed Fee data: fee brackets mapping estimate ranges to a fee amount.
        modelBuilder.Entity<Fee>().HasData([
            new Fee { FeeId = 1, EstimateStartLimit = 5000, EstimateEndLimit = 10000, fees = 1000 },
            new Fee { FeeId = 2, EstimateStartLimit = 10000, EstimateEndLimit = 20000, fees = 2000 },
            new Fee { FeeId = 3, EstimateStartLimit = 20000, EstimateEndLimit = 70000, fees = 7000 },
        ]);
    }
}
